config/routes.rb
Rails.application.routes.draw do
	root to: 'articles#index'

  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "impage/jpeg", "image/png"]

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def create
    @article = Article.new(article_params)
    @article.save
		
		flash.notice = "Article '#{@article.title}' Created!"
		redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

		flash.notice = "Article '#{@article.title}' Destroyed!"
    redirect_to articles_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"
    redirect_to article_path(@article)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/views/articles/edit.html.erb
<h1> Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
     <li>
       <%= link_to article.title, article_path(article)%>
     </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article"  %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p><%= image_tag @article.image.url(:medium) %></p>
<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>

<%= link_to "edit", edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="flash"><%= flash.notice %></p>
<%= yield %>

</body>
</html>